# Generated by Django 4.1.1 on 2022-11-04 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="name",
            field=models.CharField(
                max_length=250,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
