# Generated by Django 4.1.1 on 2022-11-04 18:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[user.models.not_rambler_validator],
                verbose_name="Email",
            ),
        ),
    ]
