# Generated by Django 4.1.1 on 2022-11-04 19:57

import datetime
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.date(2000, 1, 1),
                validators=[user.models.check_date_lt_minus_nine_years],
            ),
        ),
    ]
