# Generated by Django 4.1.1 on 2022-11-04 19:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                validators=[user.models.check_date_lt_minus_nine_years]
            ),
        ),
    ]
